package com.androidpv.java.xposed;

import com.androidpv.java.gui.DataSubmit;
import com.androidpv.java.gui.PVView;

import javax.swing.*;
import java.io.*;
import java.sql.Array;
import java.util.*;

/**
 * Created by Erin on 2/27/16.
 *
 * ModuleBuilder takes in the parsed code generated by Parser and constructs an Xposed module.
 */
public class ModuleBuilder {

    /**
     * Constructor for ModuleBuilder. Creates a text file containing the Xposed module source code.
     *
     * @param packageString
     */
    public ModuleBuilder(String packageString, String apk, String adbLoc, String sdkLoc, String uName, String adbDir) {

        System.out.println("in module builder");

        String[] packageList = packageString.split(";");

        SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {

                try {
                    String currentDir = System.getProperty("user.dir");
                    PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(currentDir +
                            "/AndroidTest/src/main/java/com/test/Tutorial.java")));

                    writer.print(MBConstants.FIRST_HALF);

                    for (int i = 0; i < packageList.length; i++) {
                        if (i > 0) {
                            writer.print(" || ");
                        }
                        writer.print(packageList[i].trim());
                    }

                    writer.print(MBConstants.SECOND_HALF);

                    writer.close();
                }
                catch (IOException e) {
                    e.printStackTrace();
                }
                return null;
            }

            @Override
            protected void done() {

                APKBuilder builder = new APKBuilder();

                if (!apk.equals("")) {
                    builder.tryToInstallAPK(adbLoc, apk);
                    PVView.getInstance().updateOutLog("APK installed at " + adbLoc + ".\n");
                }

                PVView.getInstance().updateOutLog("Building module...\n");
                builder.tryToBuildAPK(adbLoc, sdkLoc);

                int reply = JOptionPane.showConfirmDialog(null, "Your module is ready, would you like to switch views ", "Submit View", JOptionPane.OK_OPTION);
                if (reply == JOptionPane.OK_OPTION) {
                    DataSubmit.instance = new DataSubmit(uName, adbDir);
                    PVView.getInstance().setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "GOODBYE");
                }
            }
        };
        worker.execute();
    }
}
